name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy 🚀
          uses: actions/setup-node@v1
          uses: actions/checkout@v2
          with:
            node-version: 12
        - run: npm ci
        - run: npm run buildExport
        env:
            CI: true
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: main # The branch the action should deploy to.
          FOLDER: out # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch